version: '3.9'

services:

  # Backend API
  smart-brain-api:
    container_name: backend
    # image: node:14-alpine3.14
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgresql://postgres:1234@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379

  # Postgres
  postgres:
    container_name: postgres
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-brain-docker
      POSTGRES_USER: postgres
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
